version: "3.9"

services:

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: python_backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: python_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8501:8501"

volumes:
  postgres_data:
