# SPDX-FileCopyrightText: 2026 TOP Team Combat Control
# SPDX-License-Identifier: CC0-1.0

version = 3

[[annotations]]
path = "frontend/utils/image.png"
SPDX-FileCopyrightText = "2026 TOP Team Combat Control"
SPDX-License-Identifier = "GPL-3.0-or-later"